
default: &default
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: <%= ENV['XCHANGE_DATABASE_USERNAME'] %>
    password: <%= ENV['XCHANGE_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: xchange_development 

test:
  <<: *default
  database: xchange_test

production:
  <<: *default
  database: xchange_production
  username: xchange
  password: <%= ENV['XCHANGE_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
